### PR TITLE
fix install script

### PR DESCRIPTION
**Pull request by colobas**
Fix install script based on replies to issue #23

### CODE REVIEW

**Comment by colobas** [comment]
Here it goes: https://gitlab.com/nvidia/cloud-native/mig-parted/-/merge_requests/144/diffs

**Comment by elezar** [comment]
Thanks @colobas.

Could you also sign-off your commit? (running `git commit --amend -s` should do it)

**Comment by colobas** [comment]
Done. (On gitlab as well)

**Comment by elezar** [comment]
Thanks!

**Pull request merged**
