### PR TITLE
Propagate INSTANCE_PROFILE_6_SLICE constants from NVML

### PR DESCRIPTION
**Pull request by vineel-cruise**
NVML added `GPU_INSTANCE_PROFILE_6_SLICE` and `COMPUTE_INSTANCE_PROFILE_6_SLICE` constants, but these weren't propagated through `mig-parted`, meaning that 6-slice MIG profiles were not supported. This PR adds those constants to `internal/nvml/consts.go` and exposes them in `pkg/types/mig_profile.go`.

### CODE REVIEW

**Comment by elezar** [comment]
Hi @vineel-cruise. This is a read-only mirror of our development repository, so please open a merge request against https://gitlab.com/nvidia/cloud-native/mig-parted instead.

Thanks.

**Comment by klueska** [comment]
Hi @vineel-cruise As Evan said, this is just a mirror and all changes should be opened as MRs against: https://gitlab.com/nvidia/cloud-native/mig-parted

**Comment by klueska** [comment]
Since this is such a small change and obviously correct, I've gone ahead created the MR myself (with your authorship on the commit retained): https://gitlab.com/nvidia/cloud-native/mig-parted/-/merge_requests/78

Will approve / merge once CI finishes.

**Comment by vineel-cruise** [comment]
Thanks @elezar and @klueska for the help!

**Pull request closed without merging**
